import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { POST } from "./route";
import { GET } from "./[id]/route";

let storageDirectory = "";
const previousStorage = process.env.PARTCANVAS_DATA_DIR;

beforeAll(async () => {
  storageDirectory = await mkdtemp(path.join(os.tmpdir(), "partcanvas-models-"));
  process.env.PARTCANVAS_DATA_DIR = storageDirectory;
});

afterAll(async () => {
  if (previousStorage === undefined) delete process.env.PARTCANVAS_DATA_DIR;
  else process.env.PARTCANVAS_DATA_DIR = previousStorage;
  await rm(storageDirectory, { recursive: true, force: true });
});

function publishRequest(body: unknown) {
  return new Request("http://localhost/api/models", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
}

describe("hosted model API", () => {
  it("publishes, persists, retrieves, and deduplicates a validated model", async () => {
    const draft = {
      name: "Parametric label",
      description: "A printable label generated by the native text primitive.",
      source: `label = "PARTCANVAS"; // Label text\nsize = [40, 12, 2]; // [1:1:80]\nlinear_extrude(size[2]) text(label, size=size[1]);`,
      parameters: { label: "HELLO", size: [50, 14, 3] },
      tags: ["Labels", "3d-printing", "labels"],
    };
    const created = await POST(publishRequest(draft));
    const payload = await created.json();
    expect(created.status).toBe(201);
    expect(payload.url).toMatch(/^\/m\/[a-f0-9]{24}$/);
    expect(payload.model).toMatchObject({
      name: "Parametric label",
      tags: ["labels", "3d-printing"],
      parameters: { label: "HELLO", size: [50, 14, 3] },
      parameterSchema: [{ name: "label", type: "string" }, { name: "size", type: "vector" }],
    });
    expect(payload.model.metrics.triangles).toBeGreaterThan(0);

    const stored = JSON.parse(await readFile(path.join(storageDirectory, `${payload.model.id}.json`), "utf8"));
    expect(stored.id).toBe(payload.model.id);

    const retrieved = await GET(new Request(`http://localhost/api/models/${payload.model.id}`), { params: Promise.resolve({ id: payload.model.id }) });
    expect(retrieved.status).toBe(200);
    expect(retrieved.headers.get("etag")).toBe(`"${payload.model.id}"`);
    expect(retrieved.headers.get("access-control-allow-origin")).toBe("*");
    expect((await retrieved.json()).model.createdAt).toBe(payload.model.createdAt);

    const unchanged = await GET(new Request(`http://localhost/api/models/${payload.model.id}`, {
      headers: { "if-none-match": `"${payload.model.id}"` },
    }), { params: Promise.resolve({ id: payload.model.id }) });
    expect(unchanged.status).toBe(304);
    expect(await unchanged.text()).toBe("");

    const duplicate = await POST(publishRequest(draft));
    expect(duplicate.status).toBe(200);
    expect((await duplicate.json()).model.id).toBe(payload.model.id);
  });

  it("publishes one immutable record for concurrent identical requests", async () => {
    const draft = {
      name: "Concurrent block",
      source: "width = 17; cube([width, 9, 3]);",
      parameters: { width: 21 },
    };
    const responses = await Promise.all([
      POST(publishRequest(draft)),
      POST(publishRequest(draft)),
      POST(publishRequest(draft)),
    ]);
    expect(responses.map((response) => response.status).sort()).toEqual([200, 200, 201]);
    const models = await Promise.all(responses.map(async (response) => (await response.json()).model));
    expect(new Set(models.map((model) => model.id)).size).toBe(1);
    expect(new Set(models.map((model) => model.createdAt)).size).toBe(1);
  });

  it("rejects models without printable geometry and returns 404 for unknown IDs", async () => {
    const invalid = await POST(publishRequest({ name: "Empty", source: "width = 20;" }));
    expect(invalid.status).toBe(422);
    expect(await invalid.json()).toMatchObject({ error: expect.stringContaining("3D solid") });

    const missing = await GET(new Request("http://localhost/api/models/aaaaaaaaaaaaaaaaaaaaaaaa"), { params: Promise.resolve({ id: "aaaaaaaaaaaaaaaaaaaaaaaa" }) });
    expect(missing.status).toBe(404);
  });
});
